### ISSUE TITLE
SyntaxError:

### ISSUE THREAD

**Issue by Ksengine** [qweeze/nanoasgi#1]
Its crazy, raised a SyntaxError
```python
  File "nanoasgi.py", line 142
    if (m := path.match(request_path)) is not None:
          ^
SyntaxError: invalid syntax
```

**Comment by qweeze** [comment]
[Walrus operator](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions) was added to python in version 3.8, you have to update your python version to run this code ;)

**Comment by Ksengine** [comment]
I think you can make itworks with py7 easily

**Comment by qweeze** [comment]
Sure, done - 147682f51e3ce78fb4dc648badf1427ff413e612

**Comment by Ksengine** [comment]
😮 Wow,  you are quick. Thanks.
